### ISSUE TITLE
Limit on AudioRecorder

### ISSUE THREAD

**Issue by alecrespo** [RF177/Soundify#2]
Not all the devices are able to support the sampling rate, what about including a scan to set the feasible sampling rate. Like:

`public int getValidSampleRates() {
    for (int rate : new int[] {8000, 11025, 16000, 22050, 44100}) { 
        int bufferSize = AudioRecord.getMinBufferSize(rate, AudioFormat.CHANNEL_CONFIGURATION_DEFAULT, AudioFormat.ENCODING_PCM_16BIT);
        if (bufferSize > 0) {
            return rate;
        }
    }
}
`

**Comment by raphaelfuchter** [comment]
The project was abandoned, sorry.
