### ISSUE TITLE
App is throwing Null pointer exception 

### ISSUE THREAD

**Issue by rjtkumar007** [RF177/Soundify#4]
After successfully initializing the soundify ,when we are trying to startListening app is throwing below exception:-
    
> I/System.out: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference

**Comment by raphaelfuchter** [comment]
Sorry, this project has been abandoned. This error must be some incompatibility with the new versions of android.
